[package]
name = "kampfkarren/ultimate-list"
version = "0.2.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dependencies]
React = "jsdotlua/react@17.2.1"

[dev-dependencies]
ReactRoblox = "jsdotlua/react-roblox@17.2.1"

[place]
shared-packages = "game.ReplicatedStorage.Packages"
