[package]
name = "kampfkarren/ultimate-list"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["/src"]

[dependencies]
React = "jsdotlua/react@17.2.1"

[dev-dependencies]
ReactRoblox = "jsdotlua/react-roblox@17.2.1"

[place]
shared-packages = "game.ReplicatedStorage.Packages"
